package demo

type (
	MyData struct {
		Year            int `qml:"year"`
		Month           int `qml:"month"`
		PositiveResults int `qml:"positive_results"`
		TotalTests      int `qml:"total_tests"`
	}

	AutoGenerated struct {
		Data []MyData `json:"data"`
	}
)
